import Footer from "../../../components/System/Footer/Footer";
import Header from "../../../components/System/Header/Header";
import "../../../public/css/global.css";

export const metadata = {
  title: "Sistema",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt_BR">
      <body>
        <Header />
        <div className="mainContent">{children}</div>
        <Footer/>
      </body>
    </html>
  );
}
